# Generated by Django 4.1 on 2022-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=50)),
                ('repeat_password', models.TextField(max_length=50)),
                ('age', models.TextField(max_length=2)),
                ('weight', models.TextField(max_length=5)),
                ('height', models.TextField(max_length=5)),
                ('email', models.TextField(max_length=20)),
            ],
        ),
    ]
